complete tooltip component
js-tasks-ru/htmlcss-20220519_aleksandr440 pull request #10
Opened 2022-05-31 10:01 UTC by ivalexandr

2022-05-31 10:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-31 13:32 UTC, GSemikozov requested changes

2022-05-31 13:32 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  opacity: 1;
варианта только с opacity будет не достаточно, поскольку элемент все равно будет на странице и доступен, то есть сможет собой перекрывать другие, видимые, элементы. Поэтому, нужно как вариант добавлять visibility: hidden / visible

2022-06-02 15:24 UTC, GSemikozov approved these changes

2022-06-02 15:27 UTC, GSemikozov approved these changes

2022-06-02 15:27 UTC, merged