Added responsive home and components pages
js-tasks-ru/htmlcss-20220519_aleksandr440 pull request #19
Opened 2022-06-06 08:42 UTC by ivalexandr

2022-06-06 08:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-06 14:09 UTC, GSemikozov requested changes

2022-06-06 14:09 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +@media screen and (max-width: 376px) {
слишком узкий брейкпоинт (телефоны бывают и с бОльшей шириной + надо учитывать landscape). Я бы рекомендовал здесь использовать 767

2022-06-07 07:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-07 07:26 UTC, ivalexandr commented on 04-lection2/01-histogram/histogram.css
> +@media screen and (max-width: 376px) {
поменял брейкпоинт здесь, протестировал в devtools с разными устройствами и landscape, вроде нормально выглядит..

2022-06-07 17:59 UTC, GSemikozov approved these changes

2022-06-07 17:59 UTC, merged