complete skeleton
js-tasks-ru/htmlcss-20220519_aleksandr440 pull request #9
Opened 2022-05-30 09:42 UTC by ivalexandr

2022-05-30 09:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 10:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 15:10 UTC, GSemikozov requested changes

2022-05-30 15:10 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  flex:0 1 257px;
вот здесь лучше не привязываться к ограниченным значениям в пикселях, лучше запретить в контейнере перенос и выравнивать например через justify-content (второй элемент по умолчанию будет справа)

2022-05-30 15:10 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
лучше сразу в процентах

2022-05-30 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-31 07:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-31 07:16 UTC, ivalexandr commented on 04-lection2/02-skeleton/skeleton.css
> +  flex:0 1 257px;
Вроде исправил...

2022-05-31 07:16 UTC, ivalexandr commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
исправил

2022-05-31 07:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-31 10:03 UTC, GSemikozov requested changes

2022-05-31 10:13 UTC, merged